// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NCarousel: typeof import('naive-ui')['NCarousel']
    NImage: typeof import('naive-ui')['NImage']
    NImgae: typeof import('naive-ui')['NImgae']
    NPagination: typeof import('naive-ui')['NPagination']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/Index.vue')['default']
    ZoTab: typeof import('./src/components/ZoTab/Index.vue')['default']
    ZoTabs: typeof import('./src/components/ZoTabs/Index.vue')['default']
  }
}
